<?php
  require_once('../lib.php');    # Load Ela's web constants

  SetPageTitle('Research Projects');
  HTMLHeader();               # These functions are in the system wwwlib.php
  PageStart();                # library
?>

<P>
	<HR>
</P>

<H3>Current research</H3>
<P>
	<HR>
</P>


<TABLE width="">
	<TR>

		<TD valign="top" align="middle">
			<a href="http://www.cs.bham.ac.uk/~exc/Research/EPSRC_eye/index.html">
				<font size="3" face="Arial">
					<a name="ref2retina"><B>Retinal imaging</B></a>
				</font>
			</a>
			<br><br>
					<A href="http://www.cs.bham.ac.uk/~exc/Research/EPSRC_eye/index.html">
						<IMG src="http://www.cs.bham.ac.uk/~exc/Images/fundus.jpg" width="100" height="100" border="0" alt="">
			</A>
		</TD>

		<TD valign="top">
			An understanding of the
			physical interaction of light with ocular tissue is utilised to formulate a
			mathematical model capable of relating colours to retinal histology.
			Retinal maps showing the quantities and distribution of haemoglobins and macular
			pigment help with diagnosis of diabetic retinopathies and Age-related Macular Degeneration.
		</TD>

		<TD valign="top" align="middle">
			<!--<a href="http://www.cs.bham.ac.uk/~exc/Research/EPSRC_skin/epsrc_skin_project.html">-->
			<A href="http://www.cs.bham.ac.uk/~exc/Research/skincancer.php">
				<font size="3" face="Arial">
					<a name="ref2skin"><B>Skin and skin cancer</B></a>
				</font>
			</a>
			<br><br>
			<A href="http://www.cs.bham.ac.uk/~exc/Research/skincancer.php">
				<IMG src="http://www.cs.bham.ac.uk/~exc/Images/mole_rgb.jpg" width="100" height="100" border="0" style="float:right;" alt="">
			</A>
		</TD>

		<TD valign="top">
			<p>
				As an aid for early diagnosis of skin cancers
				we have developed novel image analysis methods which use
				physics-based modelling of optical properties of the skin to
				compute quantitative maps of of pigment melanin, concentration
				of blood and thickness of collagenous
				tissue. The presence of melanin in the dermis is a very
				sensitive indicator of melanoma.
			</p>
		</TD>
	</TR>

	<tr>
		<TD valign="top" align="middle">
			<a href="http://www.cs.bham.ac.uk/~exc/Images/colon_rgb.jpg">
				<font size="3" face="Arial">
					<a name="ref2colon"><B>Colon cancers</B></a>
				</font>
			</a>
			<br><br><br>
			<A href="http://www.cs.bham.ac.uk/~exc/Images/colon_rgb.jpg">
					<IMG src="http://www.cs.bham.ac.uk/~exc/Images/colon_rgb.jpg" width="100" height="100" border="0" alt="">
			</A>
		</TD>
		<TD valign="top">
			<p>
				Histological parameters characterising the colon tissue
				are computed from multispectral images of the colon and
				presented as parametric maps.
				Cancerous tissue shows much increased blood volume fraction
				and different collagen density in comparison to the normal colon.

			</p>
		</TD>

		<TD valign="top" align="middle">
			<a href="http://www.cs.bham.ac.uk/~exc/Images/microscopy1.jpg">
				<font size="3" face="Arial">
					<a name="ref2micro"><B>Quantitative microscopy</B></a>
				</font>
			</a>
			<br><br>
			<A href="http://www.cs.bham.ac.uk/~exc/Images/microscopy1.jpg">
					<IMG src="http://www.cs.bham.ac.uk/~exc/Images/microscopy1.jpg" width="100" height="100" border="0" alt="">
			</A>

		</TD>
		
		<TD valign="top">
			<p>
				Quantitative information derived from images generated by a variety
				of microscopic techniques
				(fluorescent microscopy, TIRF, DIC and their combinations)
				supports research in cancer, auto-immune diseases, cardiovascular diseases
				and drug development.
			</p>
		</TD>

	</tr>

	<tr>
		<TD valign="top" align="middle">
			<font size="3" face="Arial">
				<a name="ref2rhea"><b>Rheumatology</b></a>
			</font>
			<br>
				<br>
					<br>
						<A href="http://www.cs.bham.ac.uk/~exc/Images/rheumatology1.jpg">
							<IMG src="http://www.cs.bham.ac.uk/~exc/Images/rheumatology1.jpg" width="100" height="100" border="0" alt="">
				</A>
					</TD>
		<TD valign="top">
			<p>
				Rheumatoid arthritis can cause destruction or deformation of cartilage and bone.
				By comparing CT data of a pathological sample to a statistical
				model of non-pathological bone shape variations the nature and extent of bone destruction
				can be determined.
			</p>
		</TD>

		<TD valign="top" align="middle">
			<font size="3" face="Arial">
				<a name="ref2systems"><b>Imaging systems</b></a>
			</font>
			<br>
				<br>
					<br>
						<A href="http://www.cs.bham.ac.uk/~exc/Images/imsystems1.jpg">
							<IMG src="http://www.cs.bham.ac.uk/~exc/Images/imsystems1.jpg" width="100" height="100" border="0" alt="">
				</A>
					</TD>
		<TD valign="top">
			<p>
				Theoretical modelling of light interaction with tissues often suggests the design of
				novel imaging systems optimised for specific diagnostic targets. Our work in this
				area benefited skin cancer imaging and retinal imaging.
			</p>
		</TD>


	</tr>


</TABLE>

<P>
	<HR>
</P>
<H3>Some earlier projects</H3>
<P>
	<HR>
</P>



<div style="padding-left: 1.5em;">
	<dl>
		<dt>
			<A href="http://www.cs.bham.ac.uk/~exc/Research/Leverhulme/summary.html">
				Image interpretation via material specific spectral characterisation models</a>
			</dt>
		<dd>
			<i>
				Funded by the Leverhulme Trust
			</i>
		</dd>

		<dt>
			<a href="http://www.cs.bham.ac.uk/~exc/Images/blood_yes_2.gif">
				Automatic detection of blood deprived regions in parametric images of the skin
			</a>
		</dt>
		<dd>
			<i>
				with Francesca Satta, Florence University
			</i>
		</dd>

		<dt>
			<a href="http://www.cs.bham.ac.uk/~exc/Images/boundary.gif">
				Modelling of edge profiles in pigmented skin lesions
			</a>
		</dt>
		<dd>
			<i>
				with <a href="http://www.bccrc.ca/dept/cc/tim-lee">Tim Lee</a>, Cancer Research Institute, Vancouver, Canada
			</i>
		</dd>

		<dt>
			<a href="http://www.cs.bham.ac.uk/~exc/Images/symmetry.gif">
				Symmetry analysis
			</a>
		</dt>
		<dd>
			<i>

			</i>
		</dd>


	</dl>
</div>





<?php
  PageEnd();            # These are also in the system wwwlib.php library
  HTMLFooter();
?>

